# Generated by Django 5.2.17 on 2026-09-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("award", "Award / Achievement"),
                            ("cert", "Certification"),
                        ],
                        default="award",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("issuer", models.CharField(blank=True, max_length=200)),
                (
                    "period",
                    models.CharField(
                        blank=True, help_text="e.g. '2023 – 2024'", max_length=60
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="One point per line."),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "icon",
                    models.CharField(blank=True, default="bi-trophy", max_length=60),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.CharField(max_length=80)),
                ("username", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="bi-code-square", max_length=60
                    ),
                ),
                (
                    "stat_label",
                    models.CharField(
                        blank=True,
                        help_text="Optional, e.g. 'Problems solved'.",
                        max_length=60,
                    ),
                ),
                (
                    "stat_value",
                    models.CharField(
                        blank=True, help_text="Optional, e.g. '350+'.", max_length=60
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "platform"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=150)),
                ("field_of_study", models.CharField(blank=True, max_length=150)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("start_year", models.PositiveIntegerField()),
                (
                    "end_year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Blank = present.", null=True
                    ),
                ),
                (
                    "score",
                    models.CharField(
                        blank=True, help_text="e.g. 'Aggregate: 89.7%'", max_length=60
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Education",
                "ordering": ["order", "-start_year"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(max_length=150)),
                ("organisation", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Blank = current role.", null=True
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "tech_stack",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated technologies.",
                        max_length=300,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60)),
                ("level", models.CharField(default="Fluent", max_length=60)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=120)),
                (
                    "tagline",
                    models.CharField(
                        help_text="Short role line, e.g. 'Developer ~ Engineer'",
                        max_length=160,
                    ),
                ),
                (
                    "typed_roles",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated roles cycled by the typing animation in the hero.",
                        max_length=300,
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        help_text="Two or three paragraphs. Blank lines separate paragraphs."
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("github_username", models.CharField(blank=True, max_length=80)),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        help_text="PDF served by the download button.",
                        null=True,
                        upload_to="resume/",
                    ),
                ),
                ("available_for_work", models.BooleanField(default=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="The first active profile is the one the site renders.",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ml", "Machine Learning"),
                            ("dl", "Deep Learning"),
                            ("nlp", "NLP / LLM"),
                            ("web", "Full Stack Web"),
                            ("ds", "Data Science"),
                            ("other", "Other"),
                        ],
                        default="ml",
                        max_length=10,
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="One or two sentences shown on the card."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Full write-up on the detail page."
                    ),
                ),
                (
                    "highlights",
                    models.TextField(
                        blank=True,
                        help_text="One achievement per line — rendered as a bullet list.",
                    ),
                ),
                (
                    "tech_stack",
                    models.CharField(
                        help_text="Comma-separated technologies.", max_length=300
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("github_url", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True)),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        help_text="Small ribbon text, e.g. 'M.Tech Thesis'.",
                        max_length=60,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="bi-code-slash",
                        help_text="Bootstrap Icons class, e.g. 'bi-cpu'.",
                        max_length=60,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=250)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Skill categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=400)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullets",
                        to="core.experience",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "proficiency",
                    models.PositiveSmallIntegerField(
                        default=80, help_text="0-100, drives the progress bar width."
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="core.skillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
                "unique_together": {("category", "name")},
            },
        ),
    ]
